# Generated by Django 2.0.1 on 2021-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
