# Generated by Django 2.0.1 on 2021-04-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_car_down_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_coment',
            new_name='parent_comment',
        ),
    ]
