# Generated by Django 2.0.1 on 2021-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20210518_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_love',
            name='hot_score',
        ),
        migrations.AddField(
            model_name='car',
            name='hot_score',
            field=models.IntegerField(default=-99999),
        ),
    ]
