# Generated by Django 2.0.1 on 2021-05-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20210518_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hot_score',
            field=models.FloatField(default=-99999),
        ),
    ]
